cd Attacks
call ..\TestBuilder
cd ..\Barrels
call ..\TestBuilder
cd ..\Drowning
call ..\TestBuilder
cd ..\Floor
call ..\TestBuilder
cd ..\Gates
call ..\TestBuilder
cd ..\GatesBarrels
call ..\TestBuilder
cd ..\GatesTwoToOne
call ..\TestBuilder
cd ..\Level1
call ..\TestBuilder
cd ..\Level2
call ..\TestBuilder
cd ..\Level3
call ..\TestBuilder
cd ..\Level4
call ..\TestBuilder
cd ..\Monsters
call ..\TestBuilder
cd ..\Multiplayer
call ..\TestBuilder
cd ..\MultiplayerAttacks
call ..\TestBuilder
cd ..\MultiplayerGates
call ..\TestBuilder
cd ..\Traps
call ..\TestBuilder
cd ..\TrapsBarrels
call ..\TestBuilder
cd ..\Victory
call ..\TestBuilder
cd ..\UnlinkedGate
call ..\TestBuilder
cd ..\UnlinkedButton
call ..\TestBuilder
cd ..\GatesOneToTwo
call ..\TestBuilder
cd ..
